# Generated by Django 4.1.6 on 2023-02-04 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("s_name", models.CharField(max_length=16)),
                ("s_age", models.IntegerField(default=1)),
            ],
        ),
        migrations.DeleteModel(
            name="UserInfo",
        ),
    ]
