# Generated by Django 4.1.6 on 2023-02-04 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0003_user_delete_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(default="", max_length=16),
        ),
    ]
