# Generated by Django 4.1.6 on 2023-02-04 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0004_user_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="birthday",
            field=models.DateField(default=""),
        ),
        migrations.AddField(
            model_name="user",
            name="email",
            field=models.EmailField(default="", max_length=254),
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(default="", max_length=16),
        ),
        migrations.AddField(
            model_name="user",
            name="major",
            field=models.CharField(default="", max_length=16),
        ),
        migrations.AddField(
            model_name="user",
            name="occupation",
            field=models.CharField(default="", max_length=16),
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.IntegerField(default=""),
        ),
    ]
