# Generated by Django 4.1.6 on 2023-02-04 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0007_alter_user_birthday"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="birthday",
            field=models.DateField(default=None),
        ),
    ]
