# Generated by Django 4.1.6 on 2023-02-05 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0009_alter_user_birthday"),
    ]

    operations = [
        migrations.CreateModel(
            name="Passwords",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(default="", max_length=16)),
            ],
        ),
    ]
